/**
 * postinstall.mjs
 *
 * Runs after every `npm install`. Fixes two packages that install with
 * Windows-native binaries when npm runs on Windows, breaking the Linux
 * sandbox used by Claude agents to run vitest.
 *
 * 1. es-module-lexer — lexer.js is a single-line file containing a WASM
 *    blob as a base64 string. The Windows NTFS mount truncates it at ~14 KB,
 *    causing a SyntaxError in Node. We replace it with a thin ESM shim that
 *    re-exports from the CJS build (lexer.cjs), which survives the mount fine.
 *
 * 2. @rollup/rollup-linux-x64-gnu — already listed in optionalDependencies,
 *    but npm on Windows skips it. We detect whether we're on Linux and skip
 *    if not needed.
 */

import { existsSync, writeFileSync, statSync } from 'fs';
import { execSync } from 'child_process';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// ── 1. Fix es-module-lexer ───────────────────────────────────────────────────

const lexerJs = join(root, 'node_modules/es-module-lexer/dist/lexer.js');
const lexerCjs = join(root, 'node_modules/es-module-lexer/dist/lexer.cjs');

if (existsSync(lexerJs) && existsSync(lexerCjs)) {
  const size = statSync(lexerJs).size;
  // The real lexer.js is ~34 KB. If it's under 20 KB it's truncated.
  if (size < 20_000) {
    const shim = `/* es-module-lexer ESM shim — generated by postinstall.mjs */
/* Original lexer.js was truncated on Windows NTFS mount (${size} bytes). */
/* Re-exporting from lexer.cjs which loads correctly on all platforms.   */
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { ImportType, init, initSync, parse } = require('./lexer.cjs');
export { ImportType, init, initSync, parse };
`;
    writeFileSync(lexerJs, shim, 'utf8');
    console.log(`[postinstall] Fixed es-module-lexer/dist/lexer.js (was ${size} bytes, now shimmed)`);
  }
}

// ── 2. Fix @rollup/rollup-linux-x64-gnu on Linux ────────────────────────────

const isLinux = process.platform === 'linux';
const rollupLinux = join(root, 'node_modules/@rollup/rollup-linux-x64-gnu');

if (isLinux && !existsSync(rollupLinux)) {
  // Get the installed rollup version so we install the matching binary
  const rollupPkg = join(root, 'node_modules/rollup/package.json');
  let version = 'latest';
  if (existsSync(rollupPkg)) {
    const { version: v } = JSON.parse(
      (await import('fs')).readFileSync(rollupPkg, 'utf8')
    );
    version = v;
  }

  console.log(`[postinstall] Installing @rollup/rollup-linux-x64-gnu@${version}...`);
  try {
    execSync(`npm install @rollup/rollup-linux-x64-gnu@${version} --no-save`, {
      cwd: root,
      stdio: 'inherit',
    });
  } catch {
    // Non-fatal — tests may still work via the WASM fallback
    console.warn('[postinstall] Could not install rollup Linux binary (network may be restricted).');
  }
}
